AAA.Web/Models/Layout/LanguageSelectionViewModel.cs
using System.Collections.Generic;
using Abp.Localization;

namespace AAA.Web.Models.Layout
{
    public class LanguageSelectionViewModel
    {
        public LanguageInfo CurrentLanguage { get; set; }

        public IReadOnlyList<LanguageInfo> Languages { get; set; }
    }
}

AAA.Web/Models/Layout/TopMenuViewModel.cs
using Abp.Application.Navigation;

namespace AAA.Web.Models.Layout
{
    public class TopMenuViewModel
    {
        public UserMenu MainMenu { get; set; }

        public string ActiveMenuItemName { get; set; }
    }
}

AAA.Web/Controllers/AboutController.cs
using System.Web.Mvc;

namespace AAA.Web.Controllers
{
    public class AboutController : AAAControllerBase
    {
        public ActionResult Index()
        {
            return View();
        }
	}
}

AAA.Web/Controllers/HomeController.cs
using AAA.Web.Utils;
using System.Web.Mvc;

namespace AAA.Web.Controllers
{
    public class HomeController : AAAControllerBase
    {
        public ActionResult Index()
        {
            var fvi = SiteHelper.GetFileVersionInfo();
            ViewBag.UserName = "caizz@vanke.com";
            ViewBag.PlatformName = fvi.ProductName;
            ViewBag.PlatformVersion = fvi.FileVersion;
            ViewBag.PlatformCopyright = fvi.LegalCopyright;
            return View();
        }

        public ActionResult Portal()
        {
            return View();
        }

        public ActionResult About()
        {
            return View();
        }
    }
}

AAA.Web/Controllers/LayoutController.cs
using System.Web.Mvc;
using Abp.Application.Navigation;
using Abp.Localization;
using Abp.Runtime.Session;
using Abp.Threading;
using AAA.Web.Models.Layout;

namespace AAA.Web.Controllers
{
    public class LayoutController : AAAControllerBase
    {
        private readonly IUserNavigationManager _userNavigationManager;
        private readonly ILanguageManager _languageManager;

        public LayoutController(
            IUserNavigationManager userNavigationManager, 
            ILocalizationManager localizationManager,
            ILanguageManager languageManager)
        {
            _userNavigationManager = userNavigationManager;
            _languageManager = languageManager;
        }

        [ChildActionOnly]
        public PartialViewResult TopMenu(string activeMenu = "")
        {
            var model = new TopMenuViewModel
                        {
                            MainMenu = AsyncHelper.RunSync(() => _userNavigationManager.GetMenuAsync("MainMenu", AbpSession.ToUserIdentifier())),
                            ActiveMenuItemName = activeMenu
                        };

            return PartialView("_TopMenu", model);
        }

        [ChildActionOnly]
        public PartialViewResult LanguageSelection()
        {
            var model = new LanguageSelectionViewModel
                        {
                            CurrentLanguage = _languageManager.CurrentLanguage,
                            Languages = _languageManager.GetLanguages()
                        };

            return PartialView("_LanguageSelection", model);
        }
    }
}

AAA.Web/Views/About/Index.cshtml
@{
    ViewBag.ActiveMenu = "About"; //The menu item will be active for this page.
}
<div>
    <h1><img src="~/images/abp-logo.png" style="padding-right: 10px;" />@string.Format(L("AboutFormat"), "ASP.NET Boilerplate")</h1>
    <p>@Html.Raw(L("About_AspNetBoilerplateDescription"))</p>
    <p>@L("ForMoreInformation"): <a href="http://www.aspnetboilerplate.com"><strong>aspnetboilerplate.com</strong></a>.</p>
</div>

AAA.Web/Views/Home/Index.cshtml
@{
    ViewBag.ActiveMenu = "Home";
}
@section scripts {
    <script src="~/js/views/home/topjui.index.js"></script>
}
<div id="loading" class="loading-wrap">
    <div class="loading-content">
        <div class="loading-round"></div>
        <div class="loading-dot"></div>
    </div>
</div>
<div id="mm" class="submenubutton" style="width: 140px;">
    <div id="mm-tabclose" name="6" iconCls="fa fa-refresh">刷新</div>
    <div class="menu-sep"></div>
    <div id="Div1" name="1" iconCls="fa fa-close">关闭</div>
    <div id="mm-tabcloseother" name="3">关闭其他</div>
    <div id="mm-tabcloseall" name="2">关闭全部</div>
    <div class="menu-sep"></div>
    <div id="mm-tabcloseright" name="4">关闭右侧标签</div>
    <div id="mm-tabcloseleft" name="5">关闭左侧标签</div>
    <div class="menu-sep"></div>
    <div id="mm-newwindow" name="7">新窗口中打开</div>
</div>
<div data-toggle="topjui-layout" data-options="id:'index_layout',fit:true">
    <div id="north" class="banner" data-options="region:'north',border:false,split:false"
         style="height: 50px; padding:0;margin:0; overflow: hidden;">
        <table style="float:left;border-spacing:0px;">
            <tr>
                <td class="webname">
                    <span class="fa fa-cloud fa-lg" style="font-size:26px; padding-right:8px;"></span>
                    @ViewBag.PlatformName
                </td>
                <td class="collapseMenu" style="text-align: center;cursor: pointer;">
                    <span class="fa fa-chevron-circle-left" style="font-size: 18px;"></span>
                </td>
                <td>
                    <table id="topmenucontent" cellpadding="0" cellspacing="0">
                        <tr>
                            <td id="1325" title="实时监控" class="topmenu selected systemName">
                                <a class="l-btn-text bannerMenu" href="javascript:void(0)">
                                    <p>
                                        <lable class="fa fa-video-camera"></lable>
                                    </p>
                                    <p>
                                        <span style="white-space:nowrap;">
                                            &nbsp;&nbsp;
                                            实时监控
                                            &nbsp;&nbsp;
                                        </span>
                                    </p>
                                </a>
                            </td>
                            <td id="60" title="业务管理" class="topmenu systemName">
                                <a class="l-btn-text bannerMenu" href="javascript:void(0)">
                                    <p>
                                        <lable class="fa fa-book"></lable>
                                    </p>
                                    <p>
                                        <span style="white-space:nowrap;">
                                            &nbsp;&nbsp;
                                            业务管理
                                            &nbsp;&nbsp;
                                        </span>
                                    </p>
                                </a>
                            </td>
                            <td id="9000" title="数据管理" class="topmenu systemName">
                                <a class="l-btn-text bannerMenu" href="javascript:void(0)" target="_blank">
                                    <p>
                                        <lable class="fa fa-database"></lable>
                                    </p>
                                    <p>
                                        <span style="white-space:nowrap;">
                                            &nbsp;&nbsp;
                                            数据管理
                                            &nbsp;&nbsp;
                                        </span>
                                    </p>
                                </a>
                            </td>
                            <td id="9001" title="系统设置" class="topmenu systemName">
                                <a class="l-btn-text bannerMenu" href="javascript:void(0)" target="_blank">
                                    <p>
                                        <lable class="fa fa-cog"></lable>
                                    </p>
                                    <p>
                                        <span style="white-space:nowrap;">
                                            &nbsp;&nbsp;
                                            系统设置
                                            &nbsp;&nbsp;
                                        </span>
                                    </p>
                                </a>
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
        </table>
        <div style="float: right; padding-right: 10px; height: 50px; line-height: 50px;">
            <a href="javascript:void(0)" data-toggle="topjui-menubutton"
               data-options="iconCls:'fa fa-user',hasDownArrow:false"
               style="color:#fff;">@ViewBag.UserName</a>|
            <a href="javascript:void(0)" id="mb3" data-toggle="topjui-menubutton"
               data-options="menu:'#mm3',iconCls:'fa fa-cog',hasDownArrow:true" style="color:#fff;">设置</a>
            <div id="mm3" style="width:74px;">
                <div data-options="iconCls:'fa fa-info-circle'" onclick="javascript:modifyPwd(0)">个人信息</div>
                <div class="menu-sep"></div>
                <div data-options="iconCls:'fa fa-key'" onclick="javascript:modifyPwd(0)">修改密码</div>
            </div>|
            <a href="javascript:void(0)" id="mb2" data-toggle="topjui-menubutton"
               data-options="menu:'#mm2',iconCls:'fa fa-tree',hasDownArrow:true" style="color:#fff;">主题</a>|
            <div id="mm2" style="width:180px;">
                <div data-options="iconCls:'fa fa-tree blue'" onclick="changeTheme('blue')">默认主题</div>
                <div data-options="iconCls:'fa fa-tree'" onclick="changeTheme('black')">黑色主题</div>
                <div data-options="iconCls:'fa fa-tree'" onclick="changeTheme('blacklight')">黑色主题-亮</div>
                <div data-options="iconCls:'fa fa-tree red'" onclick="changeTheme('red')">红色主题</div>
                <div data-options="iconCls:'fa fa-tree red'" onclick="changeTheme('redlight')">红色主题-亮</div>
                <div data-options="iconCls:'fa fa-tree green'" onclick="changeTheme('green')">绿色主题</div>
                <div data-options="iconCls:'fa fa-tree green'" onclick="changeTheme('greenlight')">绿色主题-亮</div>
                <div data-options="iconCls:'fa fa-tree purple'" onclick="changeTheme('purple')">紫色主题</div>
                <div data-options="iconCls:'fa fa-tree purple'" onclick="changeTheme('purplelight')">紫色主题-亮</div>
                <div data-options="iconCls:'fa fa-tree blue'" onclick="changeTheme('blue')">蓝色主题</div>
                <div data-options="iconCls:'fa fa-tree blue'" onclick="changeTheme('bluelight')">蓝色主题-亮</div>
                <div data-options="iconCls:'fa fa-tree orange'" onclick="changeTheme('yellow')">橙色主题</div>
                <div data-options="iconCls:'fa fa-tree orange'" onclick="changeTheme('yellowlight')">橙色主题-亮</div>
            </div>
            <a href="javascript:void(0)" onclick="logout()" data-toggle="topjui-menubutton"
               data-options="iconCls:'fa fa-sign-out',hasDownArrow:false" style="color:#fff;">注销</a>
        </div>
    </div>

    <div id="west"
         data-options="region:'west',split:true,width:230,border:false,headerCls:'border_right',bodyCls:'border_right'"
         title="" iconCls="fa fa-dashboard">
        <div id="RightAccordion">
        </div>
    </div>

    <div id="center" data-options="region:'center',border:false" style="overflow:hidden;">
        <div id="index_tabs" style="width:100%;height:100%">
            <div title="系统首页" iconCls="fa fa-home" data-options="border:true,iframe:true,
                 content:'<iframe src=\'/Home/Portal\' scrolling=\'auto\' frameborder=\'0\' style=\'width:100%;height:100%;\'></iframe>'"></div>
        </div>
    </div>
    <div data-options="region:'south',border:true"
         style="text-align:center;height:30px;line-height:30px;border-bottom:0;overflow:hidden;">
        <span style="float:left;padding-left:5px;width:30%;text-align: left;">当前用户：@ViewBag.UserName</span>
        <span style="padding-right:5px;width:40%">
            @ViewBag.PlatformCopyright
            @*<a href="https://www.vankeservice.com/" target="_blank">万科物业</a>
                <a href="http://www.miitbeian.gov.cn" target="_blank"></a>*@
        </span>
        <span style="float:right;padding-right:5px;width:30%;text-align: right;">
            版本：@ViewBag.PlatformVersion
            <script></script>
        </span>
    </div>
</div>

<!--[if lte IE 8]>
<div id="ie6-warning">
    <p>您正在使用低版本浏览器，在本页面可能会导致部分功能无法使用，建议您升级到
        <a href="http://www.microsoft.com/china/windows/internet-explorer/" target="_blank">IE9或以上版本的浏览器</a>
        或使用<a href="http://se.360.cn/" target="_blank">360安全浏览器</a>的极速模式浏览
    </p>
</div>
<![endif]-->

AAA.Web/Views/Home/Index_backup.cshtml
@{
    ViewBag.ActiveMenu = "Home"; //The menu item will be active for this page.
}
<div>
    <h1>@L("WelcomeMessage")!</h1>
    <p class="lead">@L("Home_ThisIsATemplate")</p>
    <div class="row">
        <div class="col-md-4">
            <h3>ASP.NET MVC</h3>
            <p>
                @L("Home_AspNetDescription")
            </p>
            <a class="btn btn-primary btn-sm" href="http://asp.net/mvc">@L("LearnMore")..</a>
        </div>
        <div class="col-md-4">
            <h3>ASP.NET Boilerplate</h3>
            <p>
                @L("Home_AspNetBoilerplateDescription")
            </p>
            <a class="btn btn-primary btn-sm" href="http://aspnetboilerplate.com">@L("LearnMore")..</a>
        </div>
        <div class="col-md-4">
            <h3>@L("Others")</h3>
            <p>
                @L("Home_OtherTools")
            </p>
        </div>
    </div>
</div>

AAA.Web/Views/Home/Portal.cshtml
@{
    ViewData["Title"] = "Portal";
}

<h2>Portal</h2>

AAA.Web/Views/Layout/_LanguageSelection.cshtml
@model AAA.Web.Models.Layout.LanguageSelectionViewModel
<li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        <i class="@Model.CurrentLanguage.Icon"></i>
        <span>@Model.CurrentLanguage.DisplayName</span>
        <b class="caret"></b>
    </a>
    <ul class="dropdown-menu">
        @foreach (var language in Model.Languages)
        {
            if (language.Name != Model.CurrentLanguage.Name)
            {
                <li><a href="@Url.Action("ChangeCulture", "AbpLocalization")?cultureName=@(language.Name)&returnUrl=@(Request.Url)"><i class="@language.Icon"></i> @language.DisplayName</a></li>
            }
        }
    </ul>
</li>

AAA.Web/Views/Layout/_TopMenu.cshtml
@using Abp.Collections.Extensions
@using AAA.Web.Views
@model AAA.Web.Models.Layout.TopMenuViewModel
@{
    var calculateMenuUrl = new Func<string, string>((url) =>
    {
        if (string.IsNullOrEmpty(url))
        {
            return ApplicationPath;
        }

        if (UrlChecker.IsRooted(url))
        {
            return url;
        }

        return ApplicationPath + url;
    });
}
@foreach (var menuItem in Model.MainMenu.Items)
{
    <li class="@(Model.ActiveMenuItemName == menuItem.Name ? "active" : "")">
        @if (menuItem.Items.IsNullOrEmpty())
        {
            <a href="@calculateMenuUrl(menuItem.Url)">
                @if (!string.IsNullOrWhiteSpace(menuItem.Icon))
                {
                    <i class="@menuItem.Icon"></i>
                }
                @menuItem.DisplayName
            </a>
        }
        else
        {
            <a href="" data-toggle="dropdown">
                @if (!string.IsNullOrWhiteSpace(menuItem.Icon))
                {
                    <i class="@menuItem.Icon"></i>
                }
                @menuItem.DisplayName
            </a>
            <ul class="dropdown-menu">
                @foreach (var subMenuItem in menuItem.Items)
                {
                    <li>
                        <a href="@calculateMenuUrl(subMenuItem.Url)">
                            @if (!string.IsNullOrWhiteSpace(subMenuItem.Icon))
                            {
                                <i class="@subMenuItem.Icon"></i>
                            }
                            @subMenuItem.DisplayName
                        </a>
                    </li>
                }
            </ul>
        }
    </li>
}

AAA.Web/Views/Shared/_Layout.cshtml
@using System.Threading
@using System.Web.Optimization
@using Abp.Timing
@{
    SetAntiForgeryCookie();
    var fvif = AAA.Web.Utils.SiteHelper.GetFileVersionInfo();
    var title = fvif.CompanyName + fvif.ProductName;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <!-- 避免IE使用兼容模式 -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge, chrome=1">
    <meta name="renderer" content="webkit">
    <meta name="description" content="@title">
    <meta name="author" content="caizz">
    <!-- 浏览器标签图片 -->
    <link rel="shortct icon" href="~/lib/topjui/images/favicon.ico" />
    <title>@title</title>
    <!-- Global styles -->
    <!-- TopJUI框架样式 -->
    <link type="text/css" href="~/lib/topjui/css/topjui.core.min.css" rel="stylesheet">
    <link type="text/css" href="~/lib/topjui/themes/default/topjui.blue.css" rel="stylesheet" id="dynamicTheme" />
    <!-- FontAwesome字体图标 -->
    <link type="text/css" href="~/lib/topjui/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
    <!-- View specific styles -->
    @RenderSection("styles", required: false)
    @*<script type="text/javascript">
            //This is used to get the application's root path from javascript. It's useful if you're running application in a virtual directory under IIS.
            var abp = abp || {}; abp.appPath = '@ApplicationPath';
        </script>*@

    @*<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
            <script src="@Url.Content("~/Scripts/others/html5shiv.js")"></script>
            <script src="@Url.Content("~/Scripts/others/respond.min.js")"></script>
        <![endif]-->

        @Scripts.Render("~/Bundles/vendor/js/top")*@
</head>
<body>

    @RenderBody()

    <!-- Global scripts -->
    <!-- jQuery相关引用 -->
    <script type="text/javascript" src="~/lib/topjui/plugins/jquery/jquery.min.js"></script>
    <script type="text/javascript" src="~/lib/topjui/plugins/jquery/jquery.cookie.js"></script>
    <!-- TopJUI框架配置 -->
    <script src="~/js/views/home/topjui.config.js"></script>
    <!-- TopJUI框架核心 -->
    <script type="text/javascript" src="~/lib/topjui/js/topjui.core.min.js"></script>
    <!-- TopJUI中文支持 -->
    <script type="text/javascript" src="~/lib/topjui/js/locale/topjui.lang.zh_CN.js"></script>
    @*<script>
            abp.localization.defaultSourceName = '@LocalizationSourceName';
            moment.locale('@Thread.CurrentThread.CurrentUICulture.Name.ToLower()'); //Localizing momentjs
        </script>*@
    <!-- Dynamic scripts of ABP system (They are created on runtime and can not be bundled) -->
    @*<script src="~/api/AbpServiceProxies/GetAll?v=@(Clock.Now.Ticks)"></script>
        <script src="~/AbpScripts/GetScripts?v=@(Clock.Now.Ticks)" type="text/javascript"></script>*@
    <!-- View specific scripts -->
    @RenderSection("scripts", required: false)
</body>
</html>

AAA.Web/Views/Shared/_Layout_backup.cshtml
@using System.Threading
@using System.Web.Optimization
@using Abp.Timing
@{
    SetAntiForgeryCookie();
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <link rel="shortcut icon" href="~/favicon.ico">

    <title>AAA</title>

    @Styles.Render("~/Bundles/vendor/css")
    @Styles.Render("~/Bundles/css")

    <!-- View specific styles -->
    @RenderSection("styles", required: false)

    <script type="text/javascript">
        //This is used to get the application's root path from javascript. It's useful if you're running application in a virtual directory under IIS.
        var abp = abp || {}; abp.appPath = '@ApplicationPath';
    </script>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
        <script src="@Url.Content("~/Scripts/others/html5shiv.js")"></script>
        <script src="@Url.Content("~/Scripts/others/respond.min.js")"></script>
    <![endif]-->

    @Scripts.Render("~/Bundles/vendor/js/top")

</head>
<body>
    @Html.Partial("_TopBar")

    <div class="container">
        @RenderBody()
    </div>

    @Scripts.Render("~/Bundles/vendor/js/bottom")
    @Scripts.Render("~/Bundles/js")

    <script>
        abp.localization.defaultSourceName = '@LocalizationSourceName';
        moment.locale('@Thread.CurrentThread.CurrentUICulture.Name.ToLower()'); //Localizing momentjs
    </script>

    <!-- Dynamic scripts of ABP system (They are created on runtime and can not be bundled) -->
    <script src="~/api/AbpServiceProxies/GetAll?v=@(Clock.Now.Ticks)"></script>
    <script src="~/AbpScripts/GetScripts?v=@(Clock.Now.Ticks)" type="text/javascript"></script>

    <!-- View specific scripts -->
    @RenderSection("scripts", required: false)
</body>
</html>

AAA.Web/Views/Shared/_TopBar.cshtml
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="~/"><i class="fa fa-cubes"></i> AAA</a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                @Html.Action("TopMenu", "Layout", new { activeMenu = ViewBag.ActiveMenu })
            </ul>
            <ul class="nav navbar-nav navbar-right">
                @Html.Action("LanguageSelection", "Layout")
            </ul>
        </div>
    </div>
</div>